[book]
authors = ["Avdushin"]
language = "ru"
multilingual = true
src = "src"
title = "WTD | What To Do - Life Calendar"


[output.html]
default-theme = "Navy"
preferred-dark-theme = "navy"
curly-quotes = true
copy-fonts = true
no-section-label = false
git-repository-icon = "fa-github"
input-404 = "not-found.md"