version: '3'
services:
  backend:
    build: ./backend
      # dockerfile: ./backend/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env.backend
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - ./backend/.env.backend
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build: ./frontend
      # dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./frontend/.env.frontend
volumes:
  pgdata:
